version: '1'

databases:
  - name: bughunter-postgres
    databaseName: bughunter
    user: bughunter
    region: singapore
    plan: free
    postgresMajorVersion: '16'
    ipAllowList: []

services:
  - type: keyvalue
    name: bughunter-redis
    region: singapore
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction

  - type: web
    name: bughunter-api
    runtime: docker
    region: singapore
    plan: free
    branch: main
    dockerContext: .
    dockerfilePath: ./infra/Dockerfile.api
    healthCheckPath: /api/health/live
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bughunter-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: bughunter-redis
          property: connectionString
      - key: WEB_ORIGIN
        value: https://bug-hunter-api.vercel.app
      - key: NODE_ENV
        value: production
      - key: SESSION_COOKIE_SAME_SITE
        value: lax
      - key: JUDGE_PROVIDER
        value: judge0
      - key: JUDGE0_API_URL
        value: https://ce.judge0.com
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        sync: false
