import type { MissionSeed } from '../types.js';

export const chapter8Missions: MissionSeed[] = [
  {
    slug: 'chapter-8-mission-1',
    chapterOrder: 8,
    order: 1,
    title: 'f-string 괄호 누락',
    description: '이름과 나이를 입력받아 "이름은 나이세"를 f-string으로 출력해야 하지만 닫는 중괄호가 빠져 NameError가 납니다. f-string의 표현식을 올바르게 닫아 출력하세요.',
    difficulty: 1,
    isBoss: false,
    bugTypeSlug: 'syntax',
    initialCode: 'name = input().strip()\nage = input().strip()\nprint(f"{name}은 {age세")\n',
    referenceSolution: 'name = input().strip()\nage = input().strip()\nprint(f"{name}은 {age}세")\n',
    tests: [
      { order: 1, input: '민수\n20\n', expectedOutput: '민수은 20세', isHidden: false },
      { order: 2, input: 'Alice\n30\n', expectedOutput: 'Alice은 30세', isHidden: false },
      { order: 3, input: 'Bob\n7\n', expectedOutput: 'Bob은 7세', isHidden: true },
    ],
    hints: ['f-string 안에서 `{age` 뒤를 확인해보세요.', '중괄호가 하나 빠져 있습니다.', '`{age}`로 닫아주세요.'],
    explanation: 'f-string의 표현식은 `{`와 `}`가 짝을 이뤄야 합니다. 닫는 괄호가 없으면 파서가 이름을 찾지 못해 오류가 납니다.',
    concepts: ['f-string', 'SyntaxError', '중괄호'],
    baseXp: 100,
  },
  {
    slug: 'chapter-8-mission-2',
    chapterOrder: 8,
    order: 2,
    title: '나이 계산 오류',
    description: '출생연도를 입력받아 만 나이를 출력해야 하지만 input()이 문자열이라 `2026 - birth`에서 TypeError로 중단됩니다. 정수로 변환해 올바른 나이를 출력하세요.',
    difficulty: 1,
    isBoss: false,
    bugTypeSlug: 'type',
    initialCode: 'birth = input().strip()\nprint(2026 - birth)\n',
    referenceSolution: 'birth = int(input().strip())\nprint(2026 - birth)\n',
    tests: [
      { order: 1, input: '2000\n', expectedOutput: '26', isHidden: false },
      { order: 2, input: '2010\n', expectedOutput: '16', isHidden: false },
      { order: 3, input: '1999\n', expectedOutput: '27', isHidden: true },
    ],
    hints: ['`2026 - birth`에서 birth는 문자열입니다.', 'input()은 항상 문자열을 반환합니다.', '`int(input().strip())`로 변환하세요.'],
    explanation: '문자열과 정수는 뺄 수 없으므로 TypeError가 납니다. input() 값을 int로 변환해야 합니다.',
    concepts: ['input()', '형변환', 'TypeError'],
    baseXp: 100,
  },
  {
    slug: 'chapter-8-mission-3',
    chapterOrder: 8,
    order: 3,
    title: '대입과 비교 혼동',
    description: '정수 한 줄을 입력받아 0보다 크면 "양수", 아니면 "0 또는 음수"를 출력해야 하지만 비교 연산자를 `=`로 써서 SyntaxError가 납니다. 비교 연산자로 고치세요.',
    difficulty: 2,
    isBoss: false,
    bugTypeSlug: 'logic',
    initialCode: 'n = int(input())\nif n = 0:\n    print("0 또는 음수")\nelse:\n    print("양수" if n > 0 else "0 또는 음수")\n',
    referenceSolution: 'n = int(input())\nif n <= 0:\n    print("0 또는 음수")\nelse:\n    print("양수")\n',
    tests: [
      { order: 1, input: '5\n', expectedOutput: '양수', isHidden: false },
      { order: 2, input: '0\n', expectedOutput: '0 또는 음수', isHidden: false },
      { order: 3, input: '-3\n', expectedOutput: '0 또는 음수', isHidden: true },
    ],
    hints: ['`=`는 대입, `==`는 비교입니다.', '조건식에는 대입을 쓸 수 없습니다.', '`n == 0` 또는 `n <= 0`으로 바꾸세요.'],
    explanation: 'Python에서 조건식에는 비교 연산자(`==`, `<=`)를 써야 합니다. `=`는 값을 넣는 연산이라 문법 오류가 납니다.',
    concepts: ['if문', '비교연산자', 'SyntaxError'],
    baseXp: 110,
  },
  {
    slug: 'chapter-8-mission-4',
    chapterOrder: 8,
    order: 4,
    title: 'range 끝값 실수',
    description: '1부터 N까지 합을 출력해야 하지만 range(N)이 0부터 시작해 결과가 1 작습니다. 1부터 N까지 포함하도록 range를 수정하세요.',
    difficulty: 2,
    isBoss: false,
    bugTypeSlug: 'loop',
    initialCode: 'n = int(input())\nprint(sum(range(n)))\n',
    referenceSolution: 'n = int(input())\nprint(sum(range(1, n+1)))\n',
    tests: [
      { order: 1, input: '5\n', expectedOutput: '15', isHidden: false },
      { order: 2, input: '1\n', expectedOutput: '1', isHidden: false },
      { order: 3, input: '10\n', expectedOutput: '55', isHidden: true },
    ],
    hints: ['range(n)은 0~n-1까지입니다.', '1부터 시작하려면 시작값을 지정해야 합니다.', '`range(1, n+1)`로 바꾸세요.'],
    explanation: 'range의 끝값은 포함되지 않습니다. 1~N 합은 `range(1, N+1)`로 구해야 합니다.',
    concepts: ['range', '반복문', 'off-by-one'],
    baseXp: 115,
  },
  {
    slug: 'chapter-8-mission-5',
    chapterOrder: 8,
    order: 5,
    title: '출력과 반환 혼동',
    description: '두 수의 합을 반환하는 함수 add가 값을 print만 하고 return을 빠뜨려 None이 출력됩니다. 합을 반환하도록 고치세요.',
    difficulty: 3,
    isBoss: false,
    bugTypeSlug: 'function',
    initialCode: 'def add(a, b):\n    print(a + b)\n\nx = int(input())\ny = int(input())\nprint(add(x, y))\n',
    referenceSolution: 'def add(a, b):\n    return a + b\n\nx = int(input())\ny = int(input())\nprint(add(x, y))\n',
    tests: [
      { order: 1, input: '2\n3\n', expectedOutput: '5', isHidden: false },
      { order: 2, input: '10\n-2\n', expectedOutput: '8', isHidden: false },
      { order: 3, input: '0\n0\n', expectedOutput: '0', isHidden: true },
    ],
    hints: ['함수는 return으로 값을 돌려줍니다.', 'print는 화면에만 보여줄 뿐입니다.', '`print(a+b)`를 `return a+b`로 바꾸세요.'],
    explanation: '함수에서 값을 밖으로 전달하려면 return이 필요합니다. print만 하면 함수는 None을 반환합니다.',
    concepts: ['함수', 'return', 'None'],
    baseXp: 125,
  },
  {
    slug: 'chapter-8-mission-6',
    chapterOrder: 8,
    order: 6,
    title: '인덱스 범위 초과',
    description: '리스트에서 마지막 값을 출력해야 하지만 고정 인덱스 5를 써서 IndexError가 납니다. 길이와 관계없이 마지막 값을 가져오도록 수정하세요.',
    difficulty: 3,
    isBoss: false,
    bugTypeSlug: 'index',
    initialCode: 'data = list(map(int, input().split()))\nprint(data[5])\n',
    referenceSolution: 'data = list(map(int, input().split()))\nprint(data[-1])\n',
    tests: [
      { order: 1, input: '1 2 3\n', expectedOutput: '3', isHidden: false },
      { order: 2, input: '10 20\n', expectedOutput: '20', isHidden: false },
      { order: 3, input: '7 8 9 10 11\n', expectedOutput: '11', isHidden: true },
    ],
    hints: ['리스트 길이는 입력마다 다릅니다.', '마지막 인덱스는 -1입니다.', '`data[-1]`을 사용하세요.'],
    explanation: '고정 인덱스는 리스트가 짧을 때 범위를 벗어납니다. `-1`은 항상 마지막 원소를 가리킵니다.',
    concepts: ['리스트', '인덱스', 'IndexError'],
    baseXp: 125,
  },
  {
    slug: 'chapter-8-mission-7',
    chapterOrder: 8,
    order: 7,
    title: '중첩 반복 변수 섞임',
    description: 'N×M 별 직사각형을 출력해야 하지만 안쪽 반복이 바깥 변수 i를 재사용해 모양이 깨집니다. 안쪽은 j를 쓰도록 고치세요.',
    difficulty: 4,
    isBoss: false,
    bugTypeSlug: 'loop',
    initialCode: 'n = int(input())\nm = int(input())\nfor i in range(n):\n    for i in range(n):\n        print("*", end="")\n    print()\n',
    referenceSolution: 'n = int(input())\nm = int(input())\nfor i in range(n):\n    for j in range(m):\n        print("*", end="")\n    print()\n',
    tests: [
      { order: 1, input: '2\n3\n', expectedOutput: '***\n***', isHidden: false },
      { order: 2, input: '3\n2\n', expectedOutput: '**\n**\n**', isHidden: false },
      { order: 3, input: '1\n5\n', expectedOutput: '*****', isHidden: true },
    ],
    hints: ['바깥 for와 안쪽 for가 같은 이름을 씁니다.', '안쪽 변수를 바꾸면 바깥 횟수가 보존됩니다.', '안쪽을 `for j in range(m):`로 바꾸세요.'],
    explanation: '같은 변수명을 중첩 반복에 쓰면 바깥 반복의 카운터가 덮어씌워져 횟수가 꼬입니다.',
    concepts: ['중첩 반복', '변수 스코프', 'for문'],
    baseXp: 135,
  },
  {
    slug: 'chapter-8-mission-8',
    chapterOrder: 8,
    order: 8,
    title: '0으로 나누기 방어',
    description: '두 정수 a b를 입력받아 a/b를 출력하지만 b가 0일 때 ZeroDivisionError로 죽습니다. 0이면 "0으로 나눌 수 없습니다"를 출력하도록 예외 처리하세요.',
    difficulty: 4,
    isBoss: false,
    bugTypeSlug: 'exception',
    initialCode: 'a, b = map(int, input().split())\nprint(a / b)\n',
    referenceSolution: 'a, b = map(int, input().split())\ntry:\n    print(a / b)\nexcept ZeroDivisionError:\n    print("0으로 나눌 수 없습니다")\n',
    tests: [
      { order: 1, input: '10 2\n', expectedOutput: '5.0', isHidden: false },
      { order: 2, input: '0 5\n', expectedOutput: '0.0', isHidden: false },
      { order: 3, input: '7 0\n', expectedOutput: '0으로 나눌 수 없습니다', isHidden: true },
    ],
    hints: ['b가 0일 때를 따로 처리해야 합니다.', 'try/except를 사용하세요.', '`ZeroDivisionError`를 잡아 메시지를 출력하세요.'],
    explanation: '0으로 나누면 예외가 발생합니다. try 블록에서 시도하고 except에서 대체 메시지를 출력해야 프로그램이 죽지 않습니다.',
    concepts: ['try/except', 'ZeroDivisionError', '예외처리'],
    baseXp: 140,
  },
  {
    slug: 'chapter-8-mission-9',
    chapterOrder: 8,
    order: 9,
    title: 'ValueError와 빈 입력',
    description: '정수 한 줄을 입력받아 2배를 출력하지만 빈 줄이나 문자가 들어오면 ValueError로 종료됩니다. 빈 입력은 "입력 없음", 숫자가 아니면 "숫자를 입력하세요"를 출력하세요.',
    difficulty: 5,
    isBoss: false,
    bugTypeSlug: 'exception',
    initialCode: 's = input().strip()\nprint(int(s) * 2)\n',
    referenceSolution: 's = input().strip()\nif s == "":\n    print("입력 없음")\nelse:\n    try:\n        print(int(s) * 2)\n    except ValueError:\n        print("숫자를 입력하세요")\n',
    tests: [
      { order: 1, input: '21\n', expectedOutput: '42', isHidden: false },
      { order: 2, input: '\n', expectedOutput: '입력 없음', isHidden: false },
      { order: 3, input: 'abc\n', expectedOutput: '숫자를 입력하세요', isHidden: true },
      { order: 4, input: '-3\n', expectedOutput: '-6', isHidden: true },
    ],
    hints: ['빈 문자열부터 검사해야 합니다.', '숫자 변환은 예외가 날 수 있습니다.', 'if로 빈값, try로 ValueError를 나누어 처리하세요.'],
    explanation: '빈 입력과 잘못된 형식은 다른 방식으로 처리해야 합니다. 빈값은 조건문으로, 변환 실패는 ValueError 예외로 잡습니다.',
    concepts: ['ValueError', '빈 입력', '예외처리'],
    baseXp: 150,
  },
  {
    slug: 'chapter-8-mission-10',
    chapterOrder: 8,
    order: 10,
    title: '재귀 종료 조건 실종',
    description: '팩토리얼을 재귀로 계산하지만 종료 조건이 없어 RecursionError가 납니다. 0이나 1일 때 1을 반환하도록 base case를 추가하세요.',
    difficulty: 5,
    isBoss: true,
    bugTypeSlug: 'function',
    initialCode: 'def fact(n):\n    return n * fact(n-1)\n\nprint(fact(int(input())))\n',
    referenceSolution: 'def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n-1)\n\nprint(fact(int(input())))\n',
    tests: [
      { order: 1, input: '5\n', expectedOutput: '120', isHidden: false },
      { order: 2, input: '0\n', expectedOutput: '1', isHidden: false },
      { order: 3, input: '3\n', expectedOutput: '6', isHidden: true },
      { order: 4, input: '1\n', expectedOutput: '1', isHidden: true },
    ],
    hints: ['재귀는 멈추는 조건이 필요합니다.', 'n이 0이나 1일 때를 생각해보세요.', '`if n <= 1: return 1`을 함수 첫 줄에 추가하세요.'],
    explanation: '재귀 함수는 반드시 종료 조건이 있어야 합니다. 그렇지 않으면 무한히 호출되어 스택이 넘칩니다.',
    concepts: ['재귀', '팩토리얼', 'RecursionError'],
    baseXp: 160,
  },
];
